### ISSUE TITLE
Deployment failed for bookshop-sidecar in kyma environment

### ISSUE THREAD

**Issue by HuangMarco** [SAP-samples/cloud-cap-samples-java#396]
Hi Colleagues,
I followed the steps there to deploy the cloud-cap-samples-java into my kyma environment for multi-tenant scenario. The other two deployments "bookshop-approuter", "bookshop-srv" can be deployed without any issues. The pods of this two deployment can be started as expected. And the deployment "bookshop-sidecar" cannot be deployed. The error is as below:

```shell
➜  cloud-cap-samples-java git:(main) ✗ k logs bookshop-sidecar-8655d85bfd-8bc7n  -n bookshop-namespace
{"level":"info","logger":"cds","timestamp":"2024-11-24T03:38:09.637Z","msg":"loaded model from 1 file(s):\n","type":"log"}
  srv/csn.json
{"level":"info","logger":"cds","timestamp":"2024-11-24T03:38:09.846Z","msg":"connect to db > hana {\n  xsappname: '65fd47c9-1bd7-4767-88be-2b6fee32575e!b645745|service-manager!b3',\n  clientid: 'sb-65fd47c9-1bd7-4767-88be-2b6fee32575e!b645745|service-manager!b3',\n  clientsecret: '...',\n  sm_url: 'https://service-manager.cfapps.eu12.hana.ondemand.com',\n  url: 'https://reference-app-vkan66ws.authentication.eu12.hana.ondemand.com'\n}","type":"log"}
{"level":"info","logger":"cds","timestamp":"2024-11-24T03:38:09.932Z","msg":"using auth strategy {\n  kind: 'jwt',\n  impl: '../layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/lib/auth/jwt-auth'\n} \n","type":"log"}
{"level":"info","logger":"cds","timestamp":"2024-11-24T03:38:09.979Z","msg":"serving cds.xt.ModelProviderService { path: '/-/cds/model-provider' }","type":"log"}
{"level":"info","logger":"cds","timestamp":"2024-11-24T03:38:09.980Z","msg":"serving cds.xt.SaasProvisioningService { path: '/-/cds/saas-provisioning' }","type":"log"}
{"level":"info","logger":"cds","timestamp":"2024-11-24T03:38:09.982Z","msg":"serving cds.xt.DeploymentService { path: '/-/cds/deployment' }","type":"log"}
{"level":"info","logger":"cds","timestamp":"2024-11-24T03:38:09.982Z","msg":"serving cds.xt.ExtensibilityService { path: '/-/cds/extensibility' }","type":"log"}
{"level":"info","logger":"cds","timestamp":"2024-11-24T03:38:09.985Z","msg":"serving cds.xt.JobsService { path: '/-/cds/jobs' }","type":"log"}

{"level":"info","logger":"cds","correlation_id":"a627fffd-2f22-4bb1-abdf-923138877726","tenant_id":"t0","timestamp":"2024-11-24T03:38:10.030Z","msg":"loaded model from 1 file(s):\n","type":"log"}
  ../layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds-mtxs/db/t0.cds
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/generic-pool/lib/ResourceRequest.js:62:17)
    at Timeout.bound (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7)
Active connections:0


Node.js v20.18.0
```

The values.yaml of the helm chart is as below:
```yaml
# yaml-language-server: $schema=./values.schema.json

global:
  domain: c-5378bd7.stage.kyma.ondemand.com
  imagePullSecret:
    name: container-registry
  image:
    registry: registry.cn-hangzhou.aliyuncs.com/ai-registry
    tag: latest
srv:
  bindings:
    saas-registry:
      serviceInstanceName: saas-registry
    service-manager:
      fromSecret: bookshop-sm
    auth:
      serviceInstanceName: xsuaa
  image:
    repository: bookshop-srv
  env:
    SPRING_PROFILES_ACTIVE: cloud
    CDS_MULTITENANCY_APPUI_TENANTSEPARATOR: "-"
    CDS_MULTITENANCY_APPUI_URL: https://{{ .Release.Name }}-approuter-{{ .Release.Namespace }}.{{ .Values.global.domain }}
    CDS_MULTITENANCY_SIDECAR_URL: http://{{ .Release.Name }}-sidecar.{{ .Release.Namespace }}.svc.cluster.local:8080
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 1G
    requests:
      ephemeral-storage: 1G
      cpu: 1000m
      memory: 1G
  health:
    liveness:
      path: /actuator/health/liveness
    readiness:
      path: /actuator/health/readiness
  expose:
    enabled: false
  networkSecurity:
    allowNamespaceInternal: true
approuter:
  image:
    repository: bookshop-approuter
  env:
    TENANT_HOST_PATTERN: ^(.*)-{{ .Release.Name }}-approuter-{{ .Release.Namespace }}.{{ .Values.global.domain }} # change if expose.host is set
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /
    readiness:
      path: /
  envFrom:
    - configMapRef:
        name: "{{ .Release.Name }}-approuter-configmap"
  bindings:
    auth:
      serviceInstanceName: xsuaa
backendDestinations:
  backend:
    service: srv
  srv-api:
    service: srv
  mtx-api:
    service: srv
sidecar:
  expose:
    enabled: false
  networkSecurity:
    allowNamespaceInternal: true
  bindings:
    auth:
      serviceInstanceName: xsuaa
    service-manager:
      fromSecret: bookshop-sm
  image:
    repository: bookshop-sidecar
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /health
      periodSeconds: 60
      failureThreshold: 3
    readiness:
      path: /health
      periodSeconds: 60
      failureThreshold: 3
saas-registry:
  serviceOfferingName: saas-registry
  servicePlanName: application
  parameters:
    displayName: bookshop
    description: A simple CAP project.
    category: "CAP Application"
    appUrls:
      onSubscriptionAsync: true
      onUnSubscriptionAsync: true
      onUpdateDependenciesAsync: true
      callbackTimeoutMillis: 300000
      getDependencies: https://{{ .Release.Name }}-approuter-{{ .Release.Namespace }}.{{ .Values.global.domain }}/mt/v1.0/subscriptions/dependencies
      onSubscription: https://{{ .Release.Name }}-approuter-{{ .Release.Namespace }}.{{ .Values.global.domain }}/mt/v1.0/subscriptions/tenants/{tenantId}
    xsappname: bookshop-{{ .Release.Namespace }}
    appName: bookshop-{{ .Release.Namespace }}
xsuaa:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    tenant-mode: shared
    oauth2-configuration:
      redirect-uris:
        - https://*.c-5378bd7.stage.kyma.ondemand.com/**
    xsappname: bookshop-{{ .Release.Namespace }}
```

Cloud you please help to suggest how to solve this issue?
Regards,
Marco
